# Generated by komorebic.exe

# 1Password
komorebic.exe float-rule exe "1Password.exe"

# Ableton Live
komorebic.exe float-rule class "AbletonVstPlugClass"
komorebic.exe float-rule class "Vst3PlugWindow"

# Adobe Creative Cloud
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "CreativeCloudDesktopWindowClass"

# Adobe Photoshop

# Adobe Premiere Pro
komorebic.exe float-rule class "DroverLord - Window class"

# Affinity Photo 2
komorebic.exe manage-rule title "Affinity Photo 2"
komorebic.exe float-rule exe "Photo.exe"

# Akiflow
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Akiflow.exe"

# Android Studio
komorebic.exe identify-object-name-change-application exe "studio64.exe"

# Anki
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "anki.exe"

# ArmCord
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ArmCord.exe"

# AutoHotkey
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "AutoHotkeyU64.exe"
komorebic.exe float-rule title "Window Spy"
komorebic.exe float-rule exe "AutoHotkeyUX.exe"

# Beeper
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Beeper.exe"

# Bitwarden
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Bitwarden.exe"

# Blitz
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Blitz.exe"

# Bloxstrap
komorebic.exe float-rule exe "Bloxstrap.exe"

# Brave Browser
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "brave.exe"

# CLion
komorebic.exe identify-object-name-change-application exe "clion64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "clion64.exe"
komorebic.exe float-rule class "SunAwtDialog"

# Calculator
komorebic.exe float-rule title "Calculator"

# Citrix Receiver
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "SelfService.exe"
komorebic.exe float-rule exe "SelfService.exe"

# Clash Verge
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Clash Verge.exe"

# Clementine
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "clementine.exe"

# CopyQ
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "copyq.exe"

# Credential Manager UI Host
komorebic.exe float-rule exe "CredentialUIBroker.exe"

# Cron
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Cron.exe"

# DS4Windows
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "DS4Windows.exe"

# Delphi applications
komorebic.exe float-rule class "TApplication"
komorebic.exe float-rule class "TWizardForm"

# Discord
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Discord.exe"
komorebic.exe identify-layered-application exe "Discord.exe"

# Discord Bot Client

# DiscordCanary
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "DiscordCanary.exe"

# DiscordDevelopment
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "DiscordDevelopment.exe"

# DiscordPTB
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "DiscordPTB.exe"

# Docker Desktop

# Dropbox
komorebic.exe float-rule exe "Dropbox.exe"

# EA Desktop Client

# Eagle
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Eagle.exe"

# ElectronMail
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ElectronMail.exe"

# Element
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Element.exe"

# Elephicon
komorebic.exe float-rule exe "Elephicon.exe"

# ElevenClock
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ElevenClock.exe"

# Elgato Camera Hub
komorebic.exe float-rule exe "Camera Hub.exe"

# Elgato Control Center
komorebic.exe float-rule exe "ControlCenter.exe"

# Elgato Wave Link
komorebic.exe float-rule exe "WaveLink.exe"

# Epic Games Launcher
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "EpicGamesLauncher.exe"

# Everything
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "EVERYTHING"

# Everything1.5a
komorebic.exe manage-rule class "EVERYTHING_(1.5a)"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "EVERYTHING_(1.5a)"

# FFMetrics
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "FFMetrics.exe"

# Figma

# Files
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Files.exe"

# Flow Launcher

# GOG Galaxy
komorebic.exe manage-rule exe "GalaxyClient.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "GalaxyClient.exe"
komorebic.exe float-rule class "Chrome_RenderWidgetHostHWND"

# GitHub Credential Manager
komorebic.exe float-rule exe "git-credential-manager.exe"

# GitHub Desktop

# GoPro Webcam
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "GoPro Webcam"

# Godot Manager
komorebic.exe manage-rule exe "GodotManager.exe"
komorebic.exe identify-object-name-change-application exe "GodotManager.exe"

# Golden Dict
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "GoldenDict.exe"

# Google Chrome
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "chrome.exe"

# Google Drive
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "GoogleDriveFS.exe"
komorebic.exe float-rule exe "GoogleDriveFS.exe"

# Guitar Rig 7
komorebic.exe float-rule exe "Guitar Rig 7.exe"

# Honeyview

# Houdoku

# IntelliJ IDEA
komorebic.exe identify-object-name-change-application exe "idea64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "idea64.exe"

# Itch.io
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "itch.exe"

# KOOK
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "KOOK.exe"

# Keyviz
komorebic.exe float-rule exe "keyviz.exe"

# Kleopatra
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "kleopatra.exe"

# Kotatogram
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Kotatogram.exe"

# LocalSend
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "localsend_app.exe"

# Logi Bolt
komorebic.exe float-rule exe "LogiBolt.exe"

# LogiTune
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "LogiTune.exe"
komorebic.exe float-rule exe "LogiTune.exe"

# Logitech G HUB
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "lghub.exe"

# Logitech Options
komorebic.exe float-rule exe "LogiOptionsUI.exe"

# Mailspring
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "mailspring.exe"

# ManicTime
komorebic.exe manage-rule exe "ManicTimeClient.exe"
komorebic.exe identify-object-name-change-application exe "ManicTimeClient.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ManicTimeClient.exe"

# ManyCam
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ManyCam.exe"

# Mattermost
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Mattermost.exe"

# Mica For Everyone

# Microsoft Active Accessibility
komorebic.exe float-rule class "#32770"

# Microsoft Excel
komorebic.exe identify-layered-application exe "EXCEL.EXE"
komorebic.exe float-rule class "_WwB"

# Microsoft Outlook
komorebic.exe identify-layered-application exe "OUTLOOK.EXE"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "OUTLOOK.EXE"
komorebic.exe float-rule class "MsoSplash"

# Microsoft PC Manager
komorebic.exe float-rule exe "MSPCManager.exe"

# Microsoft PowerPoint
komorebic.exe identify-layered-application exe "POWERPNT.EXE"

# Microsoft SQL Server Management Studio

# Microsoft Teams
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "TeamsWebView"

# Microsoft Teams classic
komorebic.exe float-rule title "Microsoft Teams Notification"
komorebic.exe float-rule title "Microsoft Teams Call"

# Microsoft Word
komorebic.exe identify-layered-application exe "WINWORD.EXE"

# Modern Flyouts
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ModernFlyoutsHost.exe"

# Morgen

# Mozilla Firefox
komorebic.exe identify-object-name-change-application exe "firefox.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "firefox.exe"
komorebic.exe float-rule class "MozillaTaskbarPreviewClass"

# MuseScore

# NVIDIA GeForce Experience

# NZXT CAM
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "NZXT CAM.exe"

# NetEase Cloud Music
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "cloudmusic.exe"

# NiceHash Miner
komorebic.exe manage-rule exe "nhm_app.exe"

# NohBoard
komorebic.exe float-rule exe "NohBoard.exe"

# Notion Enhanced
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Notion Enhanced.exe"

# OBS Studio (32-bit)
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "obs32.exe"

# OBS Studio (64-bit)
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "obs64.exe"

# ONLYOFFICE Editors
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "DocEditorsWindowClass"

# Obsidian

# OneDrive
komorebic.exe float-rule class "OneDriveReactNativeWin32WindowClass"

# OneQuick
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "OneQuick.exe"

# OpenRGB
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "OpenRGB.exe"

# Paradox Launcher
komorebic.exe float-rule exe "Paradox Launcher.exe"

# Passware Kit Forensic

# PhpStorm
komorebic.exe identify-object-name-change-application exe "phpstorm64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "phpstorm64.exe"

# Playnite
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Playnite.DesktopApp.exe"
komorebic.exe float-rule exe "Playnite.FullscreenApp.exe"

# Plexamp

# Postman

# PowerToys
komorebic.exe float-rule exe "PowerToys.ColorPickerUI.exe"
komorebic.exe float-rule exe "PowerToys.CropAndLock.exe"
komorebic.exe float-rule exe "PowerToys.ImageResizer.exe"
komorebic.exe float-rule exe "PowerToys.Peek.UI.exe"
komorebic.exe float-rule exe "PowerToys.PowerLauncher.exe"
komorebic.exe float-rule exe "PowerToys.PowerAccent.exe"

# Process Hacker
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ProcessHacker.exe"
komorebic.exe float-rule exe "ProcessHacker.exe"

# ProtonDrive
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ProtonDrive.exe"

# ProtonVPN
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ProtonVPN.exe"

# PyCharm
komorebic.exe identify-object-name-change-application exe "pycharm64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "pycharm64.exe"

# QQ
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "QQ.exe"
komorebic.exe float-rule title "图片查看器"
komorebic.exe float-rule title "群聊的聊天记录"
komorebic.exe float-rule title "语音通话"

# QtScrcpy
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "QtScrcpy.exe"

# QuickLook
komorebic.exe float-rule exe "QuickLook.exe"

# RepoZ
komorebic.exe float-rule exe "RepoZ.exe"

# Rider
komorebic.exe identify-object-name-change-application exe "rider64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "rider64.exe"
komorebic.exe float-rule title "PopupMessageWindow"

# Roblox FPS Unlocker
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "rbxfpsunlocker.exe"

# RoundedTB
komorebic.exe float-rule exe "RoundedTB.exe"

# RoundedTB
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "RoundedTB.exe"

# RustRover
komorebic.exe identify-object-name-change-application exe "rustrover64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "rustrover64.exe"

# Sandboxie Plus
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "SandMan.exe"

# ShareX
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ShareX.exe"

# Sideloadly
komorebic.exe float-rule exe "sideloadly.exe"

# Signal
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Signal.exe"

# SiriKali
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "sirikali.exe"

# Slack
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Slack.exe"

# Slack
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "slack.exe"

# Smart Install Maker
komorebic.exe float-rule class "obj_App"
komorebic.exe float-rule class "obj_Form"

# SnippingTool
komorebic.exe float-rule exe "SnippingTool.exe"

# SoulseekQt
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "SoulseekQt.exe"

# Spotify
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Spotify.exe"

# Steam

# Steam Beta
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application class "SDL_app"
komorebic.exe float-rule title "notificationtoasts_"

# Stremio
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "stremio.exe"

# System Informer
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "SystemInformer.exe"
komorebic.exe float-rule exe "SystemInformer.exe"

# SystemSettings
komorebic.exe float-rule class "Shell_Dialog"

# Task Manager
komorebic.exe float-rule class "TaskManagerWindow"

# Telegram
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Telegram.exe"

# TickTick
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "TickTick.exe"

# Total Commander
komorebic.exe float-rule class "TDLG2FILEACTIONMIN"

# TouchCursor
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "tcconfig.exe"
komorebic.exe float-rule exe "tcconfig.exe"

# TranslucentTB
komorebic.exe float-rule exe "TranslucentTB.exe"

# TranslucentTB
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "TranslucentTB.exe"

# Unity Hub
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "Unity Hub.exe"

# Unreal Editor
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "UnrealEditor.exe"

# VMware Horizon Client
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "vmware-view.exe"

# VRCX
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "VRCX.exe"

# Visual Studio
komorebic.exe identify-object-name-change-application exe "devenv.exe"

# Visual Studio Code

# Visual Studio Code - Insiders

# Voice.ai
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "VoiceAI.exe"

# WebStorm
komorebic.exe identify-object-name-change-application exe "webstorm64.exe"
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "webstorm64.exe"

# WebTorrent Desktop
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "WebTorrent.exe"

# WinZip (32-bit)
komorebic.exe float-rule exe "winzip32.exe"

# WinZip (64-bit)
komorebic.exe float-rule exe "winzip64.exe"

# Windows Console (conhost.exe)
komorebic.exe manage-rule class "ConsoleWindowClass"

# Windows Explorer
komorebic.exe float-rule class "OperationStatusWindow"
komorebic.exe float-rule title "Control Panel"

# Windows Installer
komorebic.exe float-rule exe "msiexec.exe"

# Windows Subsystem for Android
komorebic.exe float-rule class "android(splash)"

# Windows Update Standalone Installer
komorebic.exe float-rule exe "wusa.exe"

# WingetUI
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "WingetUI.exe"

# WingetUI
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "wingetui.exe"

# Wox
komorebic.exe float-rule title "Hotkey sink"

# XAMPP Control Panel
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "xampp-control.exe"

# Zebar
komorebic.exe float-rule exe "Zebar.exe"

# Zoom
komorebic.exe float-rule exe "Zoom.exe"

# komorebi-gui
komorebic.exe float-rule exe "komorebi-gui.exe"

# mpv
komorebic.exe identify-object-name-change-application class "mpv"

# mpv.net
komorebic.exe identify-object-name-change-application exe "mpvnet.exe"

# paint.net
komorebic.exe float-rule exe "paintdotnet.exe"

# pinentry
komorebic.exe float-rule exe "pinentry.exe"

# qBittorrent
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "qbittorrent.exe"

# todoist

# ueli
# If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
komorebic.exe identify-tray-application exe "ueli.exe"
komorebic.exe float-rule exe "ueli.exe"
