return {
  -- "LazyVim/LazyVim",
  -- opts = {
  --   -- Default LazyVim opts: https://www.lazyvim.org/configuration#default-settings
  --   -- colorscheme can be a string like `catppuccin` or a function that will load the colorscheme
  --   ---@type string|fun()
  --   -- colorscheme = function()
  --   --   require("tokyonight").load()
  --   -- end,
  --   colorscheme = "onedark",
  -- },
}

-- highlight                = "#e2be7d"
-- git_delete               = "#9a353d"
-- black                    = "#282c34"
-- git_change               = "#948B60"
-- color_column             = "#2d313b"
-- git_add                  = "#109868"
-- indentline               = "#3b4048"
-- purple                   = "#c678dd"
-- line_number              = "#495162"
-- comment                  = "#7f848e"
-- inlay_hint               = "#4c525c"
-- fg                       = "#abb2bf"
-- orange                   = "#d19a66"
-- white                    = "#abb2bf"
-- red                      = "#e06c75"
-- gray                     = "#5c6370"
-- cursorline               = "#2d313b"
-- selection                = "#414858"
-- virtual_text_hint        = "#7ec7d1"
-- float_bg                 = "#21252b"
-- fg_gutter_inactive       = "#abb2bf"
-- git_hunk_add             = "#43554d"
-- blue                     = "#61afef"
-- virtual_text_information = "#90c7f4"
-- virtual_text_warning     = "#edd2a1"
-- virtual_text_error       = "#e8939a"
-- bg                       = "#282c34"
-- diff_text                = "#005869"
-- fold                     = "#30333d"
-- diff_delete              = "#501b20"
-- diff_add                 = "#003e4a"
-- fg_gutter                = "#3d4350"
-- git_hunk_delete_inline   = "#6f2e2d"
-- green                    = "#98c379"
-- git_hunk_change_inline   = "#41483d"
-- cyan                     = "#56b6c2"
-- git_hunk_add_inline      = "#3f534f"
-- bg_statusline            = "#22262d"
-- git_hunk_delete          = "#502d30"
-- yellow                   = "#e5c07b"
