return {
  -- https://www.lazyvim.org/extras/util/project#projectnvim
  -- EXTRAS: project.nvim projects.nvim
  -- "ahmedkhalf/project.nvim",
  -- opts = {
  --   -- :ProjectRoot to manually save project
  --   manual_mode = true,
  -- },
  -- {
  --
  --   "nvim-neo-tree/neo-tree.nvim",
  --   opts = {
  --     sync_root_with_cwd = true,
  --     respect_buf_cwd = true,
  --     update_focused_file = {
  --       enable = true,
  --       update_root = true,
  --     },
  --   },
  -- },
}
